{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "counter-service.fullname" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
